name: Nations
version: '${project.version}'
main: pro.cloudnode.smp.nations.Nations
api-version: '1.20'
commands:
  nations:
    description: Main command for Nations
    aliases: [ n, nation ]
    usage: /<command>